from typing import Protocol, Set, Dict, Any
from .postings import PostingList

class InvertedIndex(Protocol):
    def postings(self, term: str) -> PostingList: ...
    def all_documents(self) -> PostingList: ...
    def term_posting_count(self, term: str) -> int: ...
    def add_document(self, document_id: int, tokens: list[str]) -> None: ...
    def remove_document(self, document_id: int) -> None: ...

