from re import compile, IGNORECASE

# Lists derived from https://en.wikipedia.org/wiki/Wikipedia:List_of_English_contractions
simple_contractions = {
    compile(r"\bcan'?t\b", IGNORECASE): "cannot",
    compile(r"\bcan'?t'?ve\b", IGNORECASE): "cannot have",
    compile(r"\b'?cause\b", IGNORECASE): "because",
    compile(r"\bcould'?ve\b", IGNORECASE): "could have",
    compile(r"\bcouldn'?t\b", IGNORECASE): "could not",
    compile(r"\bcouldn'?t'?ve\b", IGNORECASE): "could not have",
    compile(r"\bdidn'?t\b", IGNORECASE): "did not",
    compile(r"\bdoesn'?t\b", IGNORECASE): "does not",
    compile(r"\bdon'?t\b", IGNORECASE): "do not",
    compile(r"\bdoin'?\b", IGNORECASE): "doing",
    compile(r"\bdunno\b", IGNORECASE): "do not know",
    compile(r"\bgimme'?\b", IGNORECASE): "give me",
    compile(r"\bgoin'?\b", IGNORECASE): "going",
    compile(r"\bgonna'?\b", IGNORECASE): "going to",
    compile(r"\bhadn'?t\b", IGNORECASE): "had not",
    compile(r"\bhadn'?t'?ve\b", IGNORECASE): "had not have",
    compile(r"\bhasn'?t\b", IGNORECASE): "has not",
    compile(r"\bhaven'?t\b", IGNORECASE): "have not",
    compile(r"\bhe'?d'?ve\b", IGNORECASE): "he would have",
    compile(r"\bhow'?d\b", IGNORECASE): "how did",
    compile(r"\bhow'?d'?y\b", IGNORECASE): "how do you",
    compile(r"\bhow'?ll\b", IGNORECASE): "how will",
    compile(r"\bI'?d'?ve\b", IGNORECASE): "I would have",
    # May replace the abbreviation "im" as in Instant Messenger.
    # If this abbreviation is in your data remove the "?"
    compile(r"\bI'?m\b", IGNORECASE): "I am",
    compile(r"\bI'?ve\b", IGNORECASE): "I have",
    compile(r"\bisn'?t\b", IGNORECASE): "is not",
    compile(r"\bit'?d'?ve\b", IGNORECASE): "it would have",
    compile(r"\bkinda\b", IGNORECASE): "kind of",
    compile(r"\blet'?s\b", IGNORECASE): "let us",
    compile(r"\bma'?am\b", IGNORECASE): "madam",
    compile(r"\bmayn'?t\b", IGNORECASE): "may not",
    compile(r"\bmight'?ve\b", IGNORECASE): "might have",
    compile(r"\bmightn'?t\b", IGNORECASE): "might not",
    compile(r"\bmightn'?t'?ve\b", IGNORECASE): "might not have",
    compile(r"\bmust'?ve\b", IGNORECASE): "must have",
    compile(r"\bmustn'?t\b", IGNORECASE): "must not",
    compile(r"\bmustn'?t'?ve\b", IGNORECASE): "must not have",
    compile(r"\bnothin'?\b", IGNORECASE): "nothing",
    compile(r"\bneedn'?t\b", IGNORECASE): "need not",
    compile(r"\bneedn'?t'?ve\b", IGNORECASE): "need not have",
    compile(r"\bo'?clock\b", IGNORECASE): "of the clock",
    compile(r"\boughta\b", IGNORECASE): "ought to",
    compile(r"\boughtn'?t\b", IGNORECASE): "ought not",
    compile(r"\boughtn'?t'?ve\b", IGNORECASE): "ought not have",
    compile(r"\bshan'?t\b", IGNORECASE): "shall not",
    compile(r"\bsha'?n'?t\b", IGNORECASE): "shall not",
    compile(r"\bshan'?t'?ve\b", IGNORECASE): "shall not have",
    compile(r"\bshe'?d'?ve\b", IGNORECASE): "she would have",
    compile(r"\bshould'?ve\b", IGNORECASE): "should have",
    compile(r"\bshouldn'?t\b", IGNORECASE): "should not",
    compile(r"\bshouldn'?t'?ve\b", IGNORECASE): "should not have",
    compile(r"\bso'?ve\b", IGNORECASE): "so have",
    compile(r"\bsomethin'?\b", IGNORECASE): "something",
    compile(r"\bthat'?d'?ve\b", IGNORECASE): "that would have",
    compile(r"\bthere'?d'?ve\b", IGNORECASE): "there would have",
    compile(r"\bthey'?d'?ve\b", IGNORECASE): "they would have",
    compile(r"\bthey'?re\b", IGNORECASE): "they are",
    compile(r"\bthey'?ve\b", IGNORECASE): "they have",
    compile(r"\b'?tis\b", IGNORECASE): "it is",
    compile(r"\bto'?ve\b", IGNORECASE): "to have",
    compile(r"\bu\b(?!\.)", IGNORECASE): "you",
    compile(r"\bwasn'?t\b", IGNORECASE): "was not",
    compile(r"\bwanna'?\b", IGNORECASE): "want to",
    compile(r"\bwe'?d'?ve\b", IGNORECASE): "we would have",
    compile(r"\bwe'll\b", IGNORECASE): "we will",
    compile(r"\bwe'?ll'?ve\b", IGNORECASE): "we will have",
    compile(r"\bwe're\b", IGNORECASE): "we are",
    compile(r"\bwe'?ve\b", IGNORECASE): "we have",
    compile(r"\bweren'?t\b", IGNORECASE): "were not",
    compile(r"\bwhat'?re\b", IGNORECASE): "what are",
    compile(r"\bwhat'?ve\b", IGNORECASE): "what have",
    compile(r"\bwhen'?ve\b", IGNORECASE): "when have",
    compile(r"\bwhere'?d\b", IGNORECASE): "where did",
    compile(r"\bwhere'?ve\b", IGNORECASE): "where have",
    compile(r"\bwho'?ve\b", IGNORECASE): "who have",
    compile(r"\bwhy'?ve\b", IGNORECASE): "why have",
    compile(r"\bwill'?ve\b", IGNORECASE): "will have",
    compile(r"\bwon'?t\b", IGNORECASE): "will not",
    compile(r"\bwon'?t'?ve\b", IGNORECASE): "will not have",
    compile(r"\bwould'?ve\b", IGNORECASE): "would have",
    compile(r"\bwouldn'?t\b", IGNORECASE): "would not",
    compile(r"\bwouldn'?t'?ve\b", IGNORECASE): "would not have",
    compile(r"\by'?all\b", IGNORECASE): "you all",
    compile(r"\by'?all'?d\b", IGNORECASE): "you all would",
    compile(r"\by'?all'?d'?ve\b", IGNORECASE): "you all would have",
    compile(r"\by'?all'?re\b", IGNORECASE): "you all are",
    compile(r"\by'?all'?ve\b", IGNORECASE): "you all have",
    compile(r"\byou'?d'?ve\b", IGNORECASE): "you would have",
    compile(r"\byou'?re\b", IGNORECASE): "you are",
    compile(r"\byou'?ve\b", IGNORECASE): "you have"
}


contextual_contractions = {
    compile(r"\bain'?t\b", IGNORECASE): ["am not", "are not", "is not", "has not", "have not"],
    compile(r"\baren'?t\b", IGNORECASE): ["are not", "am not"],
    compile(r"\bhe'?d\b", IGNORECASE): ["he had", "he would"],
    compile(r"\bhe'll\b", IGNORECASE): ["he shall", "he will"],
    compile(r"\bhe'?ll'?ve\b", IGNORECASE): ["he shall have", "he will have"],
    compile(r"\bhe'?s\b", IGNORECASE): ["he has", "he is"],
    compile(r"\bhow'?s\b", IGNORECASE): ["how has", "how is", "how does"],
    # "id" is a common abbreviation for Identification.
    # If this abbreviation does NOT appear in your data add the "?"
    compile(r"\bI'd\b", IGNORECASE): ["I had", "I would"],
    compile(r"\bI'll\b", IGNORECASE): ["I shall", "I will"],
    compile(r"\bI'?ll'?ve\b", IGNORECASE): ["I shall have", "I will have"],
    compile(r"\bit'?d\b", IGNORECASE): ["it had", "it would"],
    compile(r"\bit'?ll\b", IGNORECASE): ["it shall", "it will"],
    compile(r"\bit'?ll'?ve\b", IGNORECASE): ["it shall have", "it will have"],
    # Possessive form does not have apostrophe
    compile(r"\bit's\b", IGNORECASE): ["it has", "it is"],
    compile(r"\bshe'?d\b", IGNORECASE): ["she had", "she would", "shed"],
    compile(r"\bshe'll\b", IGNORECASE): ["she shall", "she will"],
    compile(r"\bshe'?ll'?ve\b", IGNORECASE): ["she shall have", "she will have"],
    compile(r"\bshe'?s\b", IGNORECASE): ["she has", "she is"],
    # May replace the abbreviation "sos" as in Save Our Souls.
    # If this abbreviation is in your data remove the "?"
    compile(r"\bso'?s\b", IGNORECASE): ["so as", "so is"],
    compile(r"\bthat'?d\b", IGNORECASE): ["that would", "that had"],
    compile(r"\bthat'?s\b", IGNORECASE): ["that has", "that is"],
    compile(r"\bthere'?d\b", IGNORECASE): ["there had", "there would"],
    compile(r"\bthere'?s\b", IGNORECASE): ["there has", "there is"],
    compile(r"\bthey'?d\b", IGNORECASE): ["they had", "they would"],
    compile(r"\bthey'?ll\b", IGNORECASE): ["they shall", "they will"],
    compile(r"\bthey'?ll'?ve\b", IGNORECASE): ["they shall have", "they will have"],
    compile(r"\bwe'd\b", IGNORECASE): ["we had", "we would"],
    compile(r"\bwhat'?ll\b", IGNORECASE): ["what shall", "what will"],
    compile(r"\bwhat'?ll'?ve\b", IGNORECASE): ["what shall have", "what will have"],
    compile(r"\bwhat'?s\b", IGNORECASE): ["what has", "what is"],
    compile(r"\bwhen'?s\b", IGNORECASE): ["when has", "when is"],
    compile(r"\bwhere'?s\b", IGNORECASE): ["where has", "where is"],
    compile(r"\bwho'?ll\b", IGNORECASE): ["who shall", "who will"],
    compile(r"\bwho'?ll'?ve\b", IGNORECASE): ["who shall have", "who will have"],
    compile(r"\bwho'?s\b", IGNORECASE): ["who has", "who is"],
    compile(r"\bwhy'?s\b", IGNORECASE): ["why has", "why is"],
    compile(r"\byou'?d\b", IGNORECASE): ["you had", "you would"],
    compile(r"\byou'?ll\b", IGNORECASE): ["you shall", "you will"],
    compile(r"\byou'?ll'?ve\b", IGNORECASE): ["you shall have", "you will have"],
}

expansions = {
    compile(r"\bare\s+not\b", IGNORECASE): "aren't",
    compile(r"\bcannot\b", IGNORECASE): "can't",
    compile(r"\bcould\s+have\b", IGNORECASE): "could've",
    compile(r"\bcould\s+not\b", IGNORECASE): "couldn't",
    compile(r"\bdid\s+not\b", IGNORECASE): "didn't",
    compile(r"\bdoes\s+not\b", IGNORECASE): "doesn't",
    compile(r"\bdo\s+not\b", IGNORECASE): "don't",
    compile(r"\bgot\s+to\b", IGNORECASE): "gotta",
    compile(r"\bhad\s+not\b", IGNORECASE): "hadn't",
    compile(r"\bhas\s+not\b", IGNORECASE): "hasn't",
    compile(r"\bhave\s+not\b", IGNORECASE): "haven't",
    compile(r"\bhe\s+had\b", IGNORECASE): "he'd",
    compile(r"\bhe\s+would\b", IGNORECASE): "he'd",
    compile(r"\bhe\s+shall\b", IGNORECASE): "he'll",
    compile(r"\bhe\s+will\b", IGNORECASE): "he'll",
    compile(r"\bhe\s+has\b", IGNORECASE): "he's",
    compile(r"\bhe\s+is\b", IGNORECASE): "he's",
    compile(r"\bhow\s+did\b", IGNORECASE): "how'd",
    compile(r"\bhow\s+would\b", IGNORECASE): "how'd",
    compile(r"\bhow\s+will\b", IGNORECASE): "how'll",
    compile(r"\bhow\s+has\b", IGNORECASE): "how's",
    compile(r"\bhow\s+is\b", IGNORECASE): "how's",
    compile(r"\bhow\s+does\b", IGNORECASE): "how's",
    compile(r"\bI\s+had\b", IGNORECASE): "I'd",
    compile(r"\bI\s+would\b", IGNORECASE): "I'd",
    compile(r"\bI\s+shall\b", IGNORECASE): "I'll",
    compile(r"\bI\s+will\b", IGNORECASE): "I'll",
    compile(r"\bI\s+am\b", IGNORECASE): "I'm",
    compile(r"\bI\s+have\b", IGNORECASE): "I've",
    compile(r"\bis\s+not\b", IGNORECASE): "isn't",
    compile(r"\bit\s+would\b", IGNORECASE): "it'd",
    compile(r"\bit\s+shall\b", IGNORECASE): "it'll",
    compile(r"\bit\s+will\b", IGNORECASE): "it'll",
    compile(r"\bit\s+has\b", IGNORECASE): "it's",
    compile(r"\bit\s+is\b", IGNORECASE): "it's",
    compile(r"\bmay\s+have\b", IGNORECASE): "may've",
    compile(r"\bmight\s+not\b", IGNORECASE): "mightn't",
    compile(r"\bmight\s+have\b", IGNORECASE): "might've",
    compile(r"\bmust\s+not\b", IGNORECASE): "mustn't",
    compile(r"\bmust\s+have\b", IGNORECASE): "must've",
    compile(r"\bneed\s+not\b", IGNORECASE): "needn't",
    compile(r"\bof\s+the\s+clock\b", IGNORECASE): "o'clock",
    compile(r"\bought\s+not\b", IGNORECASE): "oughtn't",
    compile(r"\bshall\s+not\b", IGNORECASE): "shan't",
    compile(r"\bshe\s+had\b", IGNORECASE): "she'd",
    compile(r"\bshe\s+would\b", IGNORECASE): "she'd",
    compile(r"\bshe\s+shall\b", IGNORECASE): "she'll",
    compile(r"\bshe\s+will\b", IGNORECASE): "she'll",
    compile(r"\bshe\s+has\b", IGNORECASE): "she's",
    compile(r"\bshe\s+is\b", IGNORECASE): "she's",
    compile(r"\bshould\s+have\b", IGNORECASE): "should've",
    compile(r"\bshould\s+not\b", IGNORECASE): "shouldn't",
    compile(r"\bsomebody\s+has\b", IGNORECASE): "somebody's",
    compile(r"\bsomebody\s+is\b", IGNORECASE): "somebody's",
    compile(r"\bsomeone\s+has\b", IGNORECASE): "someone's",
    compile(r"\bsomeone\s+is\b", IGNORECASE): "someone's",
    compile(r"\bsomething\s+has\b", IGNORECASE): "something's",
    compile(r"\bsomething\s+is\b", IGNORECASE): "something's",
    compile(r"\bthat\s+shall\b", IGNORECASE): "that'll",
    compile(r"\bthat\s+will\b", IGNORECASE): "that'll",
    compile(r"\bthat\s+are\b", IGNORECASE): "that're",
    compile(r"\bthat\s+has\b", IGNORECASE): "that's",
    compile(r"\bthat\s+is\b", IGNORECASE): "that's",
    compile(r"\bthat\s+would\b", IGNORECASE): "that'd",
    compile(r"\bthat\s+had\b", IGNORECASE): "that'd",
    compile(r"\bthere\s+had\b", IGNORECASE): "there'd",
    compile(r"\bthere\s+would\b", IGNORECASE): "there'd",
    compile(r"\bthere\s+are\b", IGNORECASE): "there're",
    compile(r"\bthere\s+has\b", IGNORECASE): "there's",
    compile(r"\bthere\s+is\b", IGNORECASE): "there's",
    compile(r"\bthese\s+are\b", IGNORECASE): "these're",
    compile(r"\bthey\s+had\b", IGNORECASE): "they'd",
    compile(r"\bthey\s+would\b", IGNORECASE): "they'd",
    compile(r"\bthey\s+shall\b", IGNORECASE): "they'll",
    compile(r"\bthey\s+will\b", IGNORECASE): "they'll",
    compile(r"\bthey\s+are\b", IGNORECASE): "they're",
    compile(r"\bthey\s+have\b", IGNORECASE): "they've",
    compile(r"\bthis\s+has\b", IGNORECASE): "this's",
    compile(r"\bthis\s+is\b", IGNORECASE): "this's",
    compile(r"\bthose\s+are\b", IGNORECASE): "those're",
    compile(r"\bwas\s+not\b", IGNORECASE): "wasn't",
    compile(r"\bwe\s+had\b", IGNORECASE): "we'd",
    compile(r"\bwe\s+would\b", IGNORECASE): "we'd",
    compile(r"\bwe\s+would\s+have\b", IGNORECASE): "we'd've",
    compile(r"\bwe\s+will\b", IGNORECASE): "we'll",
    compile(r"\bwe\s+are\b", IGNORECASE): "we're",
    compile(r"\bwe\s+have\b", IGNORECASE): "we've",
    compile(r"\bwere\s+not\b", IGNORECASE): "weren't",
    compile(r"\bwhat\s+did\b", IGNORECASE): "what'd",
    compile(r"\bwhat\s+shall\b", IGNORECASE): "what'll",
    compile(r"\bwhat\s+will\b", IGNORECASE): "what'll",
    compile(r"\bwhat\s+are\b", IGNORECASE): "what're",
    compile(r"\bwhat\s+has\b", IGNORECASE): "what's",
    compile(r"\bwhat\s+is\b", IGNORECASE): "what's",
    compile(r"\bwhat\s+does\b", IGNORECASE): "what's",
    compile(r"\bwhat\s+have\b", IGNORECASE): "what've",
    compile(r"\bwhen\s+has\b", IGNORECASE): "when's",
    compile(r"\bwhen\s+is\b", IGNORECASE): "when's",
    compile(r"\bwhere\s+did\b", IGNORECASE): "where'd",
    compile(r"\bwhere\s+are\b", IGNORECASE): "where're",
    compile(r"\bwhere\s+has\b", IGNORECASE): "where's",
    compile(r"\bwhere\s+is\b", IGNORECASE): "where's",
    compile(r"\bwhere\s+does\b", IGNORECASE): "where's",
    compile(r"\bwhere\s+have\b", IGNORECASE): "where've",
    compile(r"\bwhich\s+has\b", IGNORECASE): "which's",
    compile(r"\bwhich\s+is\b", IGNORECASE): "which's",
    compile(r"\bwho\s+would\b", IGNORECASE): "who'd",
    compile(r"\bwho\s+had\b", IGNORECASE): "who'd",
    compile(r"\bwho\s+did\b", IGNORECASE): "who'd",
    compile(r"\bwho\s+would\s+have\b", IGNORECASE): "who'd've",
    compile(r"\bwho\s+shall\b", IGNORECASE): "who'll",
    compile(r"\bwho\s+will\b", IGNORECASE): "who'll",
    compile(r"\bwho\s+are\b", IGNORECASE): "who're",
    compile(r"\bwho\s+has\b", IGNORECASE): "who's",
    compile(r"\bwho\s+is\b", IGNORECASE): "who's",
    compile(r"\bwho\s+does\b", IGNORECASE): "who's",
    compile(r"\bwho\s+have\b", IGNORECASE): "who've",
    compile(r"\bwhy\s+did\b", IGNORECASE): "why'd",
    compile(r"\bwhy\s+are\b", IGNORECASE): "why're",
    compile(r"\bwhy\s+has\b", IGNORECASE): "why's",
    compile(r"\bwhy\s+is\b", IGNORECASE): "why's",
    compile(r"\bwhy\s+does\b", IGNORECASE): "why's",
    compile(r"\bwill\s+not\b", IGNORECASE): "won't",
    compile(r"\bwould\s+have\b", IGNORECASE): "would've",
    compile(r"\bwould\s+not\b", IGNORECASE): "wouldn't",
    compile(r"\byou\s+had\b", IGNORECASE): "you'd",
    compile(r"\byou\s+would\b", IGNORECASE): "you'd",
    compile(r"\byou\s+shall\b", IGNORECASE): "you'll",
    compile(r"\byou\s+will\b", IGNORECASE): "you'll",
    compile(r"\byou\s+are\b", IGNORECASE): "you're",
    compile(r"\byou\s+have\b", IGNORECASE): "you've",
}
